---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
set.seed(42)
```

# bootstrapRRust

<!-- badges: start -->
<!-- badges: end -->

The goal of bootstrapRRust is to simply demonstrate implementation of a Rust function into R.

## Installation

You can install the development version from [GitHub](https://github.com/jmbarbone/bootstrapRRust) with:

``` r
# install.packages("devtools")
devtools::install_github("jmbarbone/bootstrapRRust")
```
## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(bootstrapRRust)
run_benchmarks(x = rchisq(2000, 2), R = 5000)
```

```{r graphs}
a <- rpois(2000, 5)
x <- bootstrap_r(a, 500)
y <- bootstrap_rs(a, 500)
z <- bootstrap_loop(a, 500)

plot(density(x), col = "red", main = "Density distribution of resampling test statistics")
lines(density(y), col = "blue")
lines(density(z), col = "green")
```

