[package]
name = "myrustlib"
version = "0.1.0"
authors = ["Jordan Mark Barbone <jmbarbone@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rand = "0.7.3"
seq = "0.5"
stats = "0.0.1"
libc = "*"
