[package]
name = "myrustlib"
version = "0.1.0"
authors = ["Jordan Mark Barbone <jmbarbone@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
rand = "0.7.3"
libc = "0.2.70"