// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// bootstrap_cpp
NumericVector bootstrap_cpp(NumericVector x, int R);
RcppExport SEXP _bootstrapCppRs_bootstrap_cpp(SEXP xSEXP, SEXP RSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type R(RSEXP);
    rcpp_result_gen = Rcpp::wrap(bootstrap_cpp(x, R));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP bootstrap_rs_wrapper(SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_bootstrapCppRs_bootstrap_cpp", (DL_FUNC) &_bootstrapCppRs_bootstrap_cpp, 2},
    {"bootstrap_rs_wrapper", (DL_FUNC) &bootstrap_rs_wrapper, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_bootstrapCppRs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
