# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Bootstrap C++
#' 
#' @param x A vector of numbers
#' @param R Number of bootstraps
#' @export
bootstrap_cpp <- function(x, R) {
    .Call('_bootstrapCppRs_bootstrap_cpp', PACKAGE = 'bootstrapCppRs', x, R)
}

